{
 "title": "Istioサービスメッシュ (ネットワーク)",
 "description": "Istioサービスメッシュのネットワークを可視化する",
 "tags": [ "istio" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Namespace",
    "label": "Source Namespace",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"source|waypoint\"},source_workload_namespace)"
    }
   },
   {
    "name": "Workload",
    "label": "Source Workload",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"source|waypoint\", source_workload_namespace=~\"$Namespace\"},source_workload)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "合計リクエスト送信数/秒",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "round(sum (rate(istio_requests_total{source_workload=~\"$Workload\",source_workload_namespace=~\"$Namespace\", reporter=~\"source|waypoint\"}[$__rate_interval])), 0.01)",
     "legendFormat": "Source Workload"
    }
   ]
  },
  {
   "title": "2xxステータス受信率 (2xx/全ステータス)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "round(sum (rate(istio_requests_total{source_workload=~\"$Workload\",source_workload_namespace=~\"$Namespace\", reporter=~\"source|waypoint\",response_code!=\"4..\", response_code!=\"5..\"}[$__rate_interval])) / sum (rate(istio_requests_total{source_workload=~\"$Workload\",source_workload_namespace=~\"$Namespace\", reporter=~\"source|waypoint\"}[$__rate_interval])) * 100, 0.01)or vector(0)",
     "legendFormat": "Source Workload"
    }
   ]
  },
  {
   "title": "4xxステータス受信率 (4xx/全ステータス)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "round(sum (rate(istio_requests_total{source_workload=~\"$Workload\",source_workload_namespace=~\"$Namespace\", reporter=~\"source|waypoint\",response_code=~\"4..\"}[$__rate_interval])) / sum (rate(istio_requests_total{source_workload=~\"$Workload\",source_workload_namespace=~\"$Namespace\", reporter=~\"source|waypoint\"}[$__rate_interval])) * 100, 0.01)or vector(0)",
     "legendFormat": "Source Workload"
    }
   ]
  },
  {
   "title": "5xxステータス受信率 (5xx/全ステータス)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "round(sum (rate(istio_requests_total{source_workload=~\"$Workload\",source_workload_namespace=~\"$Namespace\", reporter=~\"source|waypoint\",response_code=~\"5..\"}[$__rate_interval])) / sum (rate(istio_requests_total{source_workload=~\"$Workload\",source_workload_namespace=~\"$Namespace\", reporter=~\"source|waypoint\"}[$__rate_interval])) * 100, 0.01)or vector(0)",
     "legendFormat": "Source Workload"
    }
   ]
  }
 ]
}