services:
  mysql:
    container_name: istio-demo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    healthcheck:
      interval: 60s
      retries: 5
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
    hostname: istio-demo.mysql.internal
    image: mysql:8.4.9
    networks:
      - istio-demo
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

volumes:
  db_data:

networks:
  istio-demo:
    external: true
