{
 "title": "Kubernetes Deployment（CPU、メモリ）",
 "description": "Kubernetes DeploymentのCPUやメモリを可視化する",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Namespace",
    "query": "label_values(kube_deployment_created, namespace)"
   },
   {
    "name": "Deployment",
    "query": "label_values(kube_deployment_created{namespace=~\"$Namespace\"}, deployment)"
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod単位のCPU使用率（実際値/limits）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\", container!=\"POD\",pod=~\"^$Deployment.*$\", namespace=~\"$Namespace\"}[1m])) by (pod) / sum(kube_pod_container_resource_limits{resource=\"cpu\", container!=\"POD\", pod=~\"^$Deployment.*$\", namespace=~\"$Namespace\"}) by (pod) * 100",
     "legendFormat": "pod: {{ pod }}"
    }
   ]
  },
  {
   "title": "コンテナ単位のCPU使用率（実際値/limits）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\", container!=\"POD\",pod=~\"^$Deployment.*$\", namespace=~\"$Namespace\"}[1m])) by (container) / sum(kube_pod_container_resource_limits{resource=\"cpu\", container!=\"POD\", pod=~\"^$Deployment.*$\", namespace=~\"$Namespace\"}) by (container) * 100",
     "legendFormat": "container: {{ container }}"
    }
   ]
  },
  { "title": "メモリ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Pod単位のメモリ使用率（実際値/limits）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\", container!=\"POD\", pod=~\"^$Deployment.*$\", namespace=~\"$Namespace\"}) by (pod) / sum(kube_pod_container_resource_limits{resource=\"memory\", container!=\"POD\", pod=~\"^$Deployment.*$\", namespace=~\"$Namespace\"}) by (pod) * 100",
     "legendFormat": "pod: {{ pod }}"
    }
   ]
  },
  {
   "title": "コンテナ単位のメモリ使用率（実際値/limits）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\", container!=\"POD\", pod=~\"^$Deployment.*$\", namespace=~\"$Namespace\"}) by (container) / sum(kube_pod_container_resource_limits{resource=\"memory\", container!=\"POD\", pod=~\"^$Deployment.*$\", namespace=~\"$Namespace\"}) by (container) * 100",
     "legendFormat": "container: {{ container }}"
    }
   ]
  }
 ]
}
{
 "title": "Kubernetes StatefulSet（CPU、メモリ）",
 "description": "Kubernetes StatefulSetのCPUやメモリを可視化する",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Namespace",
    "query": "label_values(kube_statefulset_created, namespace)"
   },
   {
    "name": "StatefulSet",
    "query": "label_values(kube_statefulset_created{namespace=~\"$Namespace\"}, statefulset)"
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod単位のCPU使用率（実際値/limits）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\", container!=\"POD\",pod=~\"^$StatefulSet.*$\", namespace=~\"$Namespace\"}[1m])) by (pod) / sum(kube_pod_container_resource_limits{resource=\"cpu\", container!=\"POD\", pod=~\"^$StatefulSet.*$\", namespace=~\"$Namespace\"}) by (pod) * 100",
     "legendFormat": "pod: {{ pod }}"
    }
   ]
  },
  {
   "title": "コンテナ単位のCPU使用率（実際値/limits）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\", container!=\"POD\",pod=~\"^$StatefulSet.*$\", namespace=~\"$Namespace\"}[1m])) by (container) / sum(kube_pod_container_resource_limits{resource=\"cpu\", container!=\"POD\", pod=~\"^$StatefulSet.*$\", namespace=~\"$Namespace\"}) by (container) * 100",
     "legendFormat": "container: {{ container }}"
    }
   ]
  },
  { "title": "メモリ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Pod単位のメモリ使用率（実際値/limits）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\", container!=\"POD\", pod=~\"^$StatefulSet.*$\", namespace=~\"$Namespace\"}) by (pod) / sum(kube_pod_container_resource_limits{resource=\"memory\", container!=\"POD\", pod=~\"^$StatefulSet.*$\", namespace=~\"$Namespace\"}) by (pod) * 100",
     "legendFormat": "pod: {{ pod }}"
    }
   ]
  },
  {
   "title": "コンテナ単位のメモリ使用率（実際値/limits）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\", container!=\"POD\", pod=~\"^$StatefulSet.*$\", namespace=~\"$Namespace\"}) by (container) / sum(kube_pod_container_resource_limits{resource=\"memory\", container!=\"POD\", pod=~\"^$StatefulSet.*$\", namespace=~\"$Namespace\"}) by (container) * 100",
     "legendFormat": "container: {{ container }}"
    }
   ]
  }
 ]
}
{
 "title": "Istioサービスメッシュ（HTTPプロトコル共通）",
 "description": "IstioのHTTPプロトコルの共通指標を可視化する",
 "tags": [ "istio" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Namespace",
    "label": "Source Namespace",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"source|waypoint\"},source_workload_namespace)"
    }
   },
   {
    "name": "Source",
    "label": "Source Workload",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"source|waypoint\", source_workload_namespace=~\"$Namespace\"},source_workload)"
    }
   },
   {
    "name": "Destination",
    "label": "Destination Workload",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"source|waypoint\", source_workload_namespace=~\"$Namespace\", source_workload=~\"$Source\"},destination_workload)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "スループット",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{source_workload=~\"$Source\",destination_workload=~\"$Destination\",source_workload_namespace=~\"$Namespace\", reporter=~\"source|waypoint\", request_protocol=~\"http|grpc\"}[5m])) by (source_workload, destination_workload) * 60",
     "legendFormat": "{{ source_workload }} ⇄ {{ destination_workload }}"
    }
   ]
  },
  {
   "title": "レスポンス時間",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(istio_request_duration_milliseconds_sum{source_workload=~\"$Source\",destination_workload=~\"$Destination\",source_workload_namespace=~\"$Namespace\", reporter=~\"source|waypoint\", request_protocol=~\"http|grpc\"}[5m])) by (source_workload, destination_workload) / sum(rate(istio_request_duration_milliseconds_count{source_workload=~\"$Source\",destination_workload=~\"$Destination\",source_workload_namespace=~\"$Namespace\", reporter=~\"source|waypoint\", request_protocol=~\"http|grpc\"}[5m])) by (source_workload, destination_workload)",
     "legendFormat": "{{ source_workload }} ⇄ {{ destination_workload }}"
    }
   ]
  },
  {
   "title": "ステータスコード単位のresponse_flagsラベル数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sort(sum(rate(istio_requests_total{source_workload=~\"$Source\",destination_workload=~\"$Destination\",source_workload_namespace=~\"$Namespace\", reporter=~\"source|waypoint\", request_protocol=~\"http|grpc\"}[5m]) * 60 ) by (source_workload, destination_workload, response_code, response_flags))",
     "legendFormat": "{{ source_workload }} ⇄  {{ destination_workload }} | {{ response_code }} | {{ response_flags }}"
    }
   ]
  },
  {
   "title": "2xxレスポンス受信率（2xxレスポンス/全レスポンス）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{source_workload=~\"$Source\",destination_workload=~\"$Destination\",source_workload_namespace=~\"$Namespace\", reporter=~\"source|waypoint\",response_code=~\"2..\",request_protocol=~\"http|grpc\"}[5m])) by (source_workload,destination_workload) / sum(rate(istio_requests_total{source_workload=~\"$Source\",destination_workload=~\"$Destination\",source_workload_namespace=~\"$Namespace\", reporter=~\"source|waypoint\",request_protocol=~\"http|grpc\"}[5m])) by (source_workload,destination_workload) * 100",
     "legendFormat": "{{ source_workload }} ⇄ {{ destination_workload }}"
    }
   ]
  },
  {
   "title": "4xxレスポンス受信率（4xxレスポンス/全レスポンス）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{source_workload=~\"$Source\",destination_workload=~\"$Destination\",source_workload_namespace=~\"$Namespace\", reporter=~\"source|waypoint\",response_code=~\"4..\",request_protocol=~\"http|grpc\"}[5m])) by (source_workload,destination_workload) / sum(rate(istio_requests_total{source_workload=~\"$Source\",destination_workload=~\"$Destination\",source_workload_namespace=~\"$Namespace\", reporter=~\"source|waypoint\",request_protocol=~\"http|grpc\"}[5m])) by (source_workload,destination_workload) * 100",
     "legendFormat": "{{ source_workload }} ⇄ {{ destination_workload }}"
    }
   ]
  },
  {
   "title": "5xxレスポンス受信率（5xxレスポンス/全レスポンス）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{source_workload=~\"$Source\",destination_workload=~\"$Destination\",source_workload_namespace=~\"$Namespace\", reporter=~\"source|waypoint\",response_code=~\"5..\",request_protocol=~\"http|grpc\"}[5m])) by (source_workload,destination_workload) / sum(rate(istio_requests_total{source_workload=~\"$Source\",destination_workload=~\"$Destination\",source_workload_namespace=~\"$Namespace\", reporter=~\"source|waypoint\",request_protocol=~\"http|grpc\"}[5m])) by (source_workload,destination_workload) * 100",
     "legendFormat": "{{ source_workload }} ⇄ {{ destination_workload }}"
    }
   ]
  },
  {
   "title": "レスポンスなし（0ステータス/全レスポンス）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{source_workload=~\"$Source\",destination_workload=~\"$Destination\",source_workload_namespace=~\"$Namespace\", reporter=~\"source|waypoint\",response_code=~\"0\",request_protocol=~\"http|grpc\"}[5m])) by (source_workload,destination_workload) / sum(rate(istio_requests_total{source_workload=~\"$Source\",destination_workload=~\"$Destination\",source_workload_namespace=~\"$Namespace\", reporter=~\"source|waypoint\",request_protocol=~\"http|grpc\"}[5m])) by (source_workload,destination_workload) * 100",
     "legendFormat": "{{ source_workload }} ⇄ {{ destination_workload }}"
    }
   ]
  }
 ]
}
{
 "title": "Istioサービスメッシュ（TCPプロトコル共通）",
 "description": "IstioのTCPプロトコルの共通指標を可視化する",
 "tags": [ "istio" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Namespace",
    "label": "Source Namespace",
    "query": {
     "query": "label_values(istio_tcp_connections_opened_total{reporter=~\"source|waypoint\"},source_workload_namespace)"
    }
   },
   {
    "name": "Source",
    "label": "Source Workload",
    "query": {
     "query": "label_values(istio_tcp_connections_opened_total{reporter=~\"source|waypoint\", source_workload_namespace=~\"$Namespace\"},source_workload)"
    }
   },
   {
    "name": "Destination",
    "label": "Destination Workload",
    "query": {
     "query": "label_values(istio_tcp_connections_opened_total{reporter=~\"source|waypoint\", source_workload_namespace=~\"$Namespace\", source_workload=~\"$Source\"},destination_workload)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "スループット",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum(rate(istio_tcp_connections_opened_total{source_workload=~\"$Source\",destination_workload=~\"$Destination\",source_workload_namespace=~\"$Namespace\", reporter=~\"source|waypoint\", request_protocol=\"tcp\"}[5m])) by (source_workload, destination_workload) * 60",
     "legendFormat": "{{ source_workload }} ⇄ {{ destination_workload }}"
    }
   ]
  },
  {
   "title": "接続単位のresponse_flagラベル数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sort(sum(rate(istio_tcp_connections_opened_total{source_workload=~\"$Source\",destination_workload=~\"$Destination\",source_workload_namespace=~\"$Namespace\", reporter=~\"source|waypoint\", request_protocol=~\"tcp\"}[5m]) * 60 ) by (source_workload, destination_workload, response_code, response_flags))",
     "legendFormat": "{{ source_workload }} ⇄  {{ destination_workload }} | {{ response_flags }}"
    }
   ]
  }
 ]
}
{
 "title": "Istioサービスメッシュ（トラフィック管理）",
 "description": "Istioのトラフィック管理を可視化する",
 "tags": [ "istio" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Namespace",
    "label": "Source Namespace",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"destination\"},source_workload_namespace)"
    }
   },
   {
    "name": "Source",
    "label": "Source Workload",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"destination\", source_workload_namespace=~\"$Namespace\"},source_workload)"
    }
   },
   {
    "name": "Destination",
    "label": "Destination Workload",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"destination\", source_workload_namespace=~\"$Namespace\", source_workload=~\"$Source\"},destination_workload)"
    }
   },
   {
    "name": "DestinationVersion",
    "label": "Destination Version",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"destination\", source_workload_namespace=~\"$Namespace\", source_workload=~\"$Source\", destination_workload=\"$Destination\"},destination_version)"
    }
   },
   {
    "name": "DestinationApp",
    "label": "Destination App",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"destination\", source_workload_namespace=~\"$Namespace\", source_workload=~\"$Source\", destination_workload=\"$Destination\"},destination_app)"
    }
   }
  ]
 },
 "panels": [
  { "title": "宛先サブセットの正常性", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "利用可能率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_lb_subsets_active{pod=~\"^$Source.*$\",namespace=~\"$Namespace\", cluster_name=~\".*\\\\|$DestinationVersion\\\\|$DestinationApp.*\"}) by (pod,cluster_name)",
     "legendFormat": "{{ pod }} ⇄ {{ cluster_name }}"
    }
   ]
  }
 ]
}
{
 "title": "Istioサービスメッシュ（信頼性管理）",
 "description": "Istioの信頼性管理を可視化する",
 "tags": [ "istio" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Namespace",
    "label": "Source Namespace",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"destination\"},source_workload_namespace)"
    }
   },
   {
    "name": "Source",
    "label": "Source Workload",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"destination\", source_workload_namespace=~\"$Namespace\"},source_workload)"
    }
   },
   {
    "name": "Destination",
    "label": "Destination Workload",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"destination\", source_workload_namespace=~\"$Namespace\", source_workload=~\"$Source\"},destination_workload)"
    }
   },
   {
    "name": "DestinationVersion",
    "label": "Destination Version",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"destination\", source_workload_namespace=~\"$Namespace\", source_workload=~\"$Source\", destination_workload=\"$Destination\"},destination_version)"
    }
   },
   {
    "name": "DestinationApp",
    "label": "Destination App",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"destination\", source_workload_namespace=~\"$Namespace\", source_workload=~\"$Source\", destination_workload=\"$Destination\"},destination_app)"
    }
   }
  ]
 },
 "panels": [
  { "title": "宛先ワークロードの正常性", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ヘルスチェックと外れ値の正常率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_membership_healthy{pod=~\"^$Source.*$\",namespace=~\"$Namespace\", cluster_name=~\".*\\\\|$DestinationVersion\\\\|$DestinationApp.*\"}) by (pod,cluster_name)  / sum(envoy_cluster_membership_total{pod=~\"^$Source.*$\",namespace=~\"$Namespace\", cluster_name=~\".*\\\\|$DestinationVersion\\\\|$DestinationApp.*\"})  by (pod,cluster_name)  * 100",
     "legendFormat": "{{ pod }} ⇄ {{ cluster_name }}"
    }
   ]
  },
  { "title": "宛先ワークロードに対するリトライ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "リトライの累計数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry{pod=~\"^$Source.*$\",namespace=~\"$Namespace\", cluster_name=~\".*\\\\|$DestinationVersion\\\\|$DestinationApp.*\"}[5m])) by (pod,cluster_name) * 60",
     "legendFormat": "{{ pod }} ⇄ {{ cluster_name }}"
    }
   ]
  },
  {
   "title": "リトライ成功率（成功数/全リトライ数）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_rq_retry_success{pod=~\"^$Source.*$\",namespace=~\"$Namespace\", cluster_name=~\".*\\\\|$DestinationVersion\\\\|$DestinationApp.*\"}) by (pod,cluster_name) / sum(envoy_cluster_upstream_rq_retry{pod=~\"^$Source.*$\",namespace=~\"$Namespace\", cluster_name=~\".*\\\\|$DestinationVersion\\\\|$DestinationApp.*\"}) by (pod,cluster_name) * 100",
     "legendFormat": "{{ pod }} ⇄ {{ cluster_name }}"
    }
   ]
  },
  {
   "title": "全リトライに失敗したリクエスト",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry_limit_exceeded{pod=~\"^$Source.*$\",namespace=~\"$Namespace\", cluster_name=~\".*\\\\|$DestinationVersion\\\\|$DestinationApp.*\"}[5m])) by (pod,cluster_name) * 60",
     "legendFormat": "{{ pod }} ⇄ {{ cluster_name }}"
    }
   ]
  },
  { "title": "宛先ワークロードに対するタイムアウト", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "通信処理タイムアウトになったリクエスト数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_timeout{pod=~\"^$Source.*$\",namespace=~\"$Namespace\", cluster_name=~\".*\\\\|$DestinationVersion\\\\|$DestinationApp.*\"}[5m])) by (pod,cluster_name) * 60",
     "legendFormat": "{{ pod }} ⇄ {{ cluster_name }}"
    }
   ]
  },
  { "title": "接続プールに基づくサーキットブレイカー", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "接続プールからの接続取得を待機しているキュー内のリクエスト数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_total{pod=~\"^$Source.*$\",namespace=~\"$Namespace\", cluster_name=~\".*\\\\|$DestinationVersion\\\\|$DestinationApp.*\"}[5m])) by (pod,cluster_name) * 60",
     "legendFormat": "{{ pod }} ⇄ {{ cluster_name }}"
    }
   ]
  },
  { "title": "外れ値検出に基づくサーキットブレイカー", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "現在排除中の宛先数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_outlier_detection_ejections_active{pod=~\"^$Source.*$\",namespace=~\"$Namespace\", cluster_name=~\".*\\\\|$DestinationVersion\\\\|$DestinationApp.*\"}) by (pod,cluster_name)  ",
     "legendFormat": "{{ pod }} ⇄ {{ cluster_name }}"
    }
   ]
  },
  {
   "title": "5xxレスポンスの連続検知数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "envoy_cluster_outlier_detection_ejections_detected_consecutive_5xx{pod=~\"^$Source.*$\",namespace=~\"$Namespace\", cluster_name=~\".*\\\\|$DestinationVersion\\\\|$DestinationApp.*\"}",
     "legendFormat": "{{ pod }} ⇄ {{ cluster_name }}"
    }
   ]
  }
 ]
}
{
 "title": "Istioサービスメッシュ（パケット暗号化）",
 "description": "Istioの証明書指標を可視化する",
 "tags": [ "istio" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Namespace",
    "label": "Source Namespace",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"source|waypoint\"},source_workload_namespace)"
    }
   },
   {
    "name": "Source",
    "label": "Source Workload",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"source|waypoint\", source_workload_namespace=~\"$Namespace\"},source_workload)"
    }
   },
   {
    "name": "Destination",
    "label": "Destination Workload",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"source|waypoint\", source_workload_namespace=~\"$Namespace\", source_workload=~\"$Source\"},destination_workload)"
    }
   },
   {
    "name": "DestinationVersion",
    "label": "Destination Version",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"destination\", source_workload_namespace=~\"$Namespace\", source_workload=~\"$Source\", destination_workload=~\"$Destination\"},destination_version)"
    }
   },
   {
    "name": "DestinationApp",
    "label": "Destination App",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"destination\", source_workload_namespace=~\"$Namespace\", source_workload=~\"$Source\", destination_workload=~\"$Destination\"},destination_app)"
    }
   }
  ]
 },
 "panels": [
  { "title": "TLS通信", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "証明書の検証以外で失敗したHTTPSリクエスト数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_ssl_connection_error{pod=~\"^$Source.*$\",namespace=~\"$Namespace\", cluster_name=~\".*\\\\|$DestinationVersion\\\\|$DestinationApp.*\"}[5m])) by (pod,cluster_name) * 60",
     "legendFormat": "{{ pod }} ⇄ {{ cluster_name }}"
    }
   ]
  },
  {
   "title": "証明書の検証に失敗したHTTPSリクエスト数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_ssl_fail_verify_no_cert{pod=~\"^$Source.*$\",namespace=~\"$Namespace\", cluster_name=~\".*\\\\|$DestinationVersion\\\\|$DestinationApp.*\"}[5m])) by (pod,cluster_name) * 60",
     "legendFormat": "{{ pod }} ⇄ {{ cluster_name }}"
    }
   ]
  }
 ]
}