service:
  name: egress

destination:
  mysql:
    host: dev.istio-demo.mysql.internal
    port: 3306
  googleapis:
    host: www.googleapis.com
    port: 443
  grafanaTempo:
    host: grafana-tempo.grafana-tempo.svc.cluster.local
    port: 4317
