{
 "title": "【すべてのDeployment】CPU・メモリ",
 "description": "Kubernetes Deploymentに関連するCPU・メモリを監視する",
 "tags": [ "metrics" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Namespace",
    "query": "label_values(kube_deployment_created, namespace)"
   },
   {
    "name": "Deployment",
    "query": "label_values(kube_deployment_created{namespace=~\"$Namespace\"}, deployment)"
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod単位のCPU使用率（実際値/limits）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\", container!=\"POD\",pod=~\"^$Deployment.*$\", namespace=~\"$Namespace\"}[1m])) by (pod) / sum(kube_pod_container_resource_limits{resource=\"cpu\", container!=\"POD\", pod=~\"^$Deployment.*$\", namespace=~\"$Namespace\"}) by (pod) * 100",
     "legendFormat": "pod: {{ pod }}"
    }
   ]
  },
  {
   "title": "コンテナ単位のCPU使用率（実際値/limits）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\", container!=\"POD\",pod=~\"^$Deployment.*$\", namespace=~\"$Namespace\"}[1m])) by (container) / sum(kube_pod_container_resource_limits{resource=\"cpu\", container!=\"POD\", pod=~\"^$Deployment.*$\", namespace=~\"$Namespace\"}) by (container) * 100",
     "legendFormat": "container: {{ container }}"
    }
   ]
  },
  { "title": "メモリ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Pod単位のメモリ使用率（実際値/limits）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\", container!=\"POD\", pod=~\"^$Deployment.*$\", namespace=~\"$Namespace\"}) by (pod) / sum(kube_pod_container_resource_limits{resource=\"memory\", container!=\"POD\", pod=~\"^$Deployment.*$\", namespace=~\"$Namespace\"}) by (pod) * 100",
     "legendFormat": "pod: {{ pod }}"
    }
   ]
  },
  {
   "title": "コンテナ単位のメモリ使用率（実際値/limits）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\", container!=\"POD\", pod=~\"^$Deployment.*$\", namespace=~\"$Namespace\"}) by (container) / sum(kube_pod_container_resource_limits{resource=\"memory\", container!=\"POD\", pod=~\"^$Deployment.*$\", namespace=~\"$Namespace\"}) by (container) * 100",
     "legendFormat": "container: {{ container }}"
    }
   ]
  }
 ]
}
{
 "title": "【すべてのStatefulSet】CPU・メモリ",
 "description": "Kubernetes StatefulSetに関連するCPU・メモリを監視する",
 "tags": [ "metrics" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Namespace",
    "query": "label_values(kube_statefulset_created, namespace)"
   },
   {
    "name": "StatefulSet",
    "query": "label_values(kube_statefulset_created{namespace=~\"$Namespace\"}, statefulset)"
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod単位のCPU使用率（実際値/limits）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\", container!=\"POD\",pod=~\"^$StatefulSet.*$\", namespace=~\"$Namespace\"}[1m])) by (pod) / sum(kube_pod_container_resource_limits{resource=\"cpu\", container!=\"POD\", pod=~\"^$StatefulSet.*$\", namespace=~\"$Namespace\"}) by (pod) * 100",
     "legendFormat": "pod: {{ pod }}"
    }
   ]
  },
  {
   "title": "コンテナ単位のCPU使用率（実際値/limits）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\", container!=\"POD\",pod=~\"^$StatefulSet.*$\", namespace=~\"$Namespace\"}[1m])) by (container) / sum(kube_pod_container_resource_limits{resource=\"cpu\", container!=\"POD\", pod=~\"^$StatefulSet.*$\", namespace=~\"$Namespace\"}) by (container) * 100",
     "legendFormat": "container: {{ container }}"
    }
   ]
  },
  { "title": "メモリ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Pod単位のメモリ使用率（実際値/limits）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\", container!=\"POD\", pod=~\"^$StatefulSet.*$\", namespace=~\"$Namespace\"}) by (pod) / sum(kube_pod_container_resource_limits{resource=\"memory\", container!=\"POD\", pod=~\"^$StatefulSet.*$\", namespace=~\"$Namespace\"}) by (pod) * 100",
     "legendFormat": "pod: {{ pod }}"
    }
   ]
  },
  {
   "title": "コンテナ単位のメモリ使用率（実際値/limits）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\", container!=\"POD\", pod=~\"^$StatefulSet.*$\", namespace=~\"$Namespace\"}) by (container) / sum(kube_pod_container_resource_limits{resource=\"memory\", container!=\"POD\", pod=~\"^$StatefulSet.*$\", namespace=~\"$Namespace\"}) by (container) * 100",
     "legendFormat": "container: {{ container }}"
    }
   ]
  }
 ]
}
{
 "title": "【サービスメッシュ内のPod】HTTPリクエスト",
 "description": "Istioに関連するHTTPプロトコルを監視する",
 "tags": [ "metrics" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Namespace",
    "label": "Source Namespace",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"source|waypoint\"},source_workload_namespace)"
    }
   },
   {
    "name": "Source",
    "label": "Source Workload",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"source|waypoint\", source_workload_namespace=~\"$Namespace\"},source_workload)"
    }
   },
   {
    "name": "Destination",
    "label": "Destination Workload",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"source|waypoint\", source_workload_namespace=~\"$Namespace\", source_workload=~\"$Source\"},destination_workload)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "リクエストのスループット",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{source_workload=~\"$Source\",destination_workload=~\"$Destination\",source_workload_namespace=~\"$Namespace\", reporter=~\"source|waypoint\", request_protocol=~\"http|grpc\"}[5m])) by (source_workload, destination_workload) * 60",
     "legendFormat": "{{ source_workload }} ⇄ {{ destination_workload }}"
    }
   ]
  },
  {
   "title": "レスポンス時間",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(istio_request_duration_milliseconds_sum{source_workload=~\"$Source\",destination_workload=~\"$Destination\",source_workload_namespace=~\"$Namespace\", reporter=~\"source|waypoint\", request_protocol=~\"http|grpc\"}[5m])) by (source_workload, destination_workload) / sum(rate(istio_request_duration_milliseconds_count{source_workload=~\"$Source\",destination_workload=~\"$Destination\",source_workload_namespace=~\"$Namespace\", reporter=~\"source|waypoint\", request_protocol=~\"http|grpc\"}[5m])) by (source_workload, destination_workload)",
     "legendFormat": "{{ source_workload }} ⇄ {{ destination_workload }}"
    }
   ]
  },
  {
   "title": "各response_flagsラベルで集計したレスポンスステータス数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sort(sum(rate(istio_requests_total{source_workload=~\"$Source\",destination_workload=~\"$Destination\",source_workload_namespace=~\"$Namespace\", reporter=~\"source|waypoint\", request_protocol=~\"http|grpc\"}[5m]) * 60 ) by (source_workload, destination_workload, response_code, response_flags))",
     "legendFormat": "{{ source_workload }} ⇄  {{ destination_workload }} | {{ response_code }} | {{ response_flags }}"
    }
   ]
  },
  {
   "title": "2xxレスポンスの受信率（2xxレスポンス/全レスポンス）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{source_workload=~\"$Source\",destination_workload=~\"$Destination\",source_workload_namespace=~\"$Namespace\", reporter=~\"source|waypoint\",response_code=~\"2..\",request_protocol=~\"http|grpc\"}[5m])) by (source_workload,destination_workload) / sum(rate(istio_requests_total{source_workload=~\"$Source\",destination_workload=~\"$Destination\",source_workload_namespace=~\"$Namespace\", reporter=~\"source|waypoint\",request_protocol=~\"http|grpc\"}[5m])) by (source_workload,destination_workload) * 100",
     "legendFormat": "{{ source_workload }} ⇄ {{ destination_workload }}"
    }
   ]
  },
  {
   "title": "4xxレスポンスの受信率（4xxレスポンス/全レスポンス）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{source_workload=~\"$Source\",destination_workload=~\"$Destination\",source_workload_namespace=~\"$Namespace\", reporter=~\"source|waypoint\",response_code=~\"4..\",request_protocol=~\"http|grpc\"}[5m])) by (source_workload,destination_workload) / sum(rate(istio_requests_total{source_workload=~\"$Source\",destination_workload=~\"$Destination\",source_workload_namespace=~\"$Namespace\", reporter=~\"source|waypoint\",request_protocol=~\"http|grpc\"}[5m])) by (source_workload,destination_workload) * 100",
     "legendFormat": "{{ source_workload }} ⇄ {{ destination_workload }}"
    }
   ]
  },
  {
   "title": "5xxレスポンスの受信率（5xxレスポンス/全レスポンス）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{source_workload=~\"$Source\",destination_workload=~\"$Destination\",source_workload_namespace=~\"$Namespace\", reporter=~\"source|waypoint\",response_code=~\"5..\",request_protocol=~\"http|grpc\"}[5m])) by (source_workload,destination_workload) / sum(rate(istio_requests_total{source_workload=~\"$Source\",destination_workload=~\"$Destination\",source_workload_namespace=~\"$Namespace\", reporter=~\"source|waypoint\",request_protocol=~\"http|grpc\"}[5m])) by (source_workload,destination_workload) * 100",
     "legendFormat": "{{ source_workload }} ⇄ {{ destination_workload }}"
    }
   ]
  },
  {
   "title": "レスポンス未返信（0ステータス/全レスポンス）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{source_workload=~\"$Source\",destination_workload=~\"$Destination\",source_workload_namespace=~\"$Namespace\", reporter=~\"source|waypoint\",response_code=~\"0\",request_protocol=~\"http|grpc\"}[5m])) by (source_workload,destination_workload) / sum(rate(istio_requests_total{source_workload=~\"$Source\",destination_workload=~\"$Destination\",source_workload_namespace=~\"$Namespace\", reporter=~\"source|waypoint\",request_protocol=~\"http|grpc\"}[5m])) by (source_workload,destination_workload) * 100",
     "legendFormat": "{{ source_workload }} ⇄ {{ destination_workload }}"
    }
   ]
  }
 ]
}
{
 "title": "【サービスメッシュ内のPod】TCP接続",
 "description": "Istioに関連するTCP接続を監視する",
 "tags": [ "metrics" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Namespace",
    "label": "Source Namespace",
    "query": {
     "query": "label_values(istio_tcp_connections_opened_total{reporter=~\"source|waypoint\"},source_workload_namespace)"
    }
   },
   {
    "name": "Source",
    "label": "Source Workload",
    "query": {
     "query": "label_values(istio_tcp_connections_opened_total{reporter=~\"source|waypoint\", source_workload_namespace=~\"$Namespace\"},source_workload)"
    }
   },
   {
    "name": "Destination",
    "label": "Destination Workload",
    "query": {
     "query": "label_values(istio_tcp_connections_opened_total{reporter=~\"source|waypoint\", source_workload_namespace=~\"$Namespace\", source_workload=~\"$Source\"},destination_workload)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "新しく確立されたTCP接続数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum(rate(istio_tcp_connections_opened_total{source_workload=~\"$Source\",destination_workload=~\"$Destination\",source_workload_namespace=~\"$Namespace\", reporter=~\"source|waypoint\", request_protocol=\"tcp\"}[5m])) by (source_workload, destination_workload) * 60",
     "legendFormat": "{{ source_workload }} ⇄ {{ destination_workload }}"
    }
   ]
  },
  {
   "title": "各response_flagラベルで集計したTCP接続数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sort(sum(rate(istio_tcp_connections_opened_total{source_workload=~\"$Source\",destination_workload=~\"$Destination\",source_workload_namespace=~\"$Namespace\", reporter=~\"source|waypoint\", request_protocol=~\"tcp\"}[5m]) * 60 ) by (source_workload, destination_workload, response_flags))",
     "legendFormat": "{{ source_workload }} ⇄  {{ destination_workload }} | {{ response_flags }}"
    }
   ]
  }
 ]
}
{
 "title": "【サービスメッシュ内のPod】トラフィック管理",
 "description": "Istioに関連するトラフィック管理を監視する",
 "tags": [ "metrics" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Namespace",
    "label": "Source Namespace",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"destination\"},source_workload_namespace)"
    }
   },
   {
    "name": "Source",
    "label": "Source Workload",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"destination\", source_workload_namespace=~\"$Namespace\"},source_workload)"
    }
   },
   {
    "name": "Destination",
    "label": "Destination Workload",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"destination\", source_workload_namespace=~\"$Namespace\", source_workload=~\"$Source\"},destination_workload)"
    }
   },
   {
    "name": "DestinationVersion",
    "label": "Destination Version",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"destination\", source_workload_namespace=~\"$Namespace\", source_workload=~\"$Source\", destination_workload=\"$Destination\"},destination_version)"
    }
   },
   {
    "name": "DestinationApp",
    "label": "Destination App",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"destination\", source_workload_namespace=~\"$Namespace\", source_workload=~\"$Source\", destination_workload=\"$Destination\"},destination_app)"
    }
   }
  ]
 },
 "panels": [
  { "title": "ゾーンに基づく負荷分散", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "同じゾーンへのL4/L7振り分け率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_lb_zone_routing_all_directly{pod=~\"^$Source.*$\", namespace=~\"$Namespace\", cluster_name=~\".*\\\\|$DestinationVersion\\\\|$DestinationApp.*\"}[5m])) by (pod, cluster_name) / sum(rate(envoy_cluster_lb_zone_routing_sampled{pod=~\"^$Source.*$\", namespace=~\"$Namespace\", cluster_name=~\".*\\\\|$DestinationVersion\\\\|$DestinationApp.*\"}[5m])) by (pod, cluster_name) ",
     "legendFormat": "{{ pod }} ⇄ {{ cluster_name }}"
    }
   ]
  },
  {
   "title": "異なるゾーンへのL4/L7振り分け率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_lb_zone_routing_cross_zone{pod=~\"^$Source.*$\", namespace=~\"$Namespace\", cluster_name=~\".*\\\\|$DestinationVersion\\\\|$DestinationApp.*\"}[5m])) by (pod, cluster_name) / sum(rate(envoy_cluster_lb_zone_routing_sampled{pod=~\"^$Source.*$\", namespace=~\"$Namespace\", cluster_name=~\".*\\\\|$DestinationVersion\\\\|$DestinationApp.*\"}[5m])) by (pod, cluster_name) ",
     "legendFormat": "{{ pod }} ⇄ {{ cluster_name }}"
    }
   ]
  }
 ]
}
{
 "title": "【サービスメッシュ内のPod】信頼性管理",
 "description": "Istioに関連する信頼性管理を監視する",
 "tags": [ "metrics" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Namespace",
    "label": "Source Namespace",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"destination\"},source_workload_namespace)"
    }
   },
   {
    "name": "Source",
    "label": "Source Workload",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"destination\", source_workload_namespace=~\"$Namespace\"},source_workload)"
    }
   },
   {
    "name": "Destination",
    "label": "Destination Workload",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"destination\", source_workload_namespace=~\"$Namespace\", source_workload=~\"$Source\"},destination_workload)"
    }
   },
   {
    "name": "DestinationVersion",
    "label": "Destination Version",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"destination\", source_workload_namespace=~\"$Namespace\", source_workload=~\"$Source\", destination_workload=\"$Destination\"},destination_version)"
    }
   },
   {
    "name": "DestinationApp",
    "label": "Destination App",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"destination\", source_workload_namespace=~\"$Namespace\", source_workload=~\"$Source\", destination_workload=\"$Destination\"},destination_app)"
    }
   }
  ]
 },
 "panels": [
  { "title": "通信元コンポーネントから見た宛先の正常性", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "宛先envoyクラスターの正常率（正常数/全メンバー数）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_membership_healthy{pod=~\"^$Source.*$\",namespace=~\"$Namespace\", cluster_name=~\".*\\\\|$DestinationVersion\\\\|$DestinationApp.*\"}) by (pod,cluster_name)  / sum(envoy_cluster_membership_total{pod=~\"^$Source.*$\",namespace=~\"$Namespace\", cluster_name=~\".*\\\\|$DestinationVersion\\\\|$DestinationApp.*\"}) by (pod,cluster_name)  * 100",
     "legendFormat": "{{ pod }} ⇄ {{ cluster_name }}"
    }
   ]
  },
  { "title": "宛先コンポーネントに対するリトライ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "リトライの実行数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry{pod=~\"^$Source.*$\",namespace=~\"$Namespace\", cluster_name=~\".*\\\\|$DestinationVersion\\\\|$DestinationApp.*\"}[5m])) by (pod,cluster_name) * 60",
     "legendFormat": "{{ pod }} ⇄ {{ cluster_name }}"
    }
   ]
  },
  {
   "title": "リトライの成功率（成功数/全リトライ数）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_rq_retry_success{pod=~\"^$Source.*$\",namespace=~\"$Namespace\", cluster_name=~\".*\\\\|$DestinationVersion\\\\|$DestinationApp.*\"}) by (pod,cluster_name) / sum(envoy_cluster_upstream_rq_retry{pod=~\"^$Source.*$\",namespace=~\"$Namespace\", cluster_name=~\".*\\\\|$DestinationVersion\\\\|$DestinationApp.*\"}) by (pod,cluster_name) * 100",
     "legendFormat": "{{ pod }} ⇄ {{ cluster_name }}"
    }
   ]
  },
  {
   "title": "全リトライに失敗したリクエスト率（全失敗数/全リクエスト数）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(envoy_cluster_upstream_rq_retry_limit_exceeded{pod=~\"^$Source.*$\",namespace=~\"$Namespace\",cluster_name=~\".*\\\\|$DestinationVersion\\\\|$DestinationApp.*\"}[5m])) by (pod,cluster_name)) / (sum(rate(envoy_cluster_upstream_rq_total{pod=~\"^$Source.*$\",namespace=~\"$Namespace\",cluster_name=~\".*\\\\|$DestinationVersion\\\\|$DestinationApp.*\"}[5m])) by (pod,cluster_name)) * 100",
     "legendFormat": "{{ pod }} ⇄ {{ cluster_name }}"
    }
   ]
  },
  { "title": "宛先コンポーネントに対するタイムアウト", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "通信処理タイムアウトになったリクエスト率（全タイムアウト数/全リクエスト数）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(envoy_cluster_upstream_rq_timeout{pod=~\"^$Source.*$\",namespace=~\"$Namespace\",cluster_name=~\".*\\\\|$DestinationVersion\\\\|$DestinationApp.*\"}[5m])) by (pod,cluster_name)) / (sum(rate(envoy_cluster_upstream_rq_total{pod=~\"^$Source.*$\",namespace=~\"$Namespace\",cluster_name=~\".*\\\\|$DestinationVersion\\\\|$DestinationApp.*\"}[5m])) by (pod,cluster_name)) * 100",
     "legendFormat": "{{ pod }} ⇄ {{ cluster_name }}"
    }
   ]
  },
  { "title": "接続プールに基づくサーキットブレイカー", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "接続プールからの接続取得を待機しているキュー内のリクエスト数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_total{pod=~\"^$Source.*$\",namespace=~\"$Namespace\", cluster_name=~\".*\\\\|$DestinationVersion\\\\|$DestinationApp.*\"}[5m])) by (pod,cluster_name) * 60",
     "legendFormat": "{{ pod }} ⇄ {{ cluster_name }}"
    }
   ]
  },
  { "title": "外れ値検出に基づくサーキットブレイカー", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "現在排除中の宛先メンバー率（排除数/全メンバー数）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(envoy_cluster_outlier_detection_ejections_active{pod=~\"^$Source.*$\",namespace=~\"$Namespace\",cluster_name=~\".*\\\\|$DestinationVersion\\\\|$DestinationApp.*\"}) by (pod,cluster_name)) / (sum(envoy_cluster_membership_total{pod=~\"^$Source.*$\",namespace=~\"$Namespace\",cluster_name=~\".*\\\\|$DestinationVersion\\\\|$DestinationApp.*\"}) by (pod,cluster_name)) * 100",
     "legendFormat": "{{ pod }} ⇄ {{ cluster_name }}"
    }
   ]
  },
  {
   "title": "5xxレスポンスの連続検知数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "envoy_cluster_outlier_detection_ejections_detected_consecutive_5xx{pod=~\"^$Source.*$\",namespace=~\"$Namespace\", cluster_name=~\".*\\\\|$DestinationVersion\\\\|$DestinationApp.*\"}",
     "legendFormat": "{{ pod }} ⇄ {{ cluster_name }}"
    }
   ]
  }
 ]
}
{
 "title": "【サービスメッシュ内のPod】パケット暗号化",
 "description": "Istioに関連するパケット暗号化を監視する",
 "tags": [ "metrics" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Namespace",
    "label": "Source Namespace",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"source|waypoint\"},source_workload_namespace)"
    }
   },
   {
    "name": "Source",
    "label": "Source Workload",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"source|waypoint\", source_workload_namespace=~\"$Namespace\"},source_workload)"
    }
   },
   {
    "name": "Destination",
    "label": "Destination Workload",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"source|waypoint\", source_workload_namespace=~\"$Namespace\", source_workload=~\"$Source\"},destination_workload)"
    }
   },
   {
    "name": "DestinationVersion",
    "label": "Destination Version",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"destination\", source_workload_namespace=~\"$Namespace\", source_workload=~\"$Source\", destination_workload=~\"$Destination\"},destination_version)"
    }
   },
   {
    "name": "DestinationApp",
    "label": "Destination App",
    "query": {
     "query": "label_values(istio_requests_total{reporter=~\"destination\", source_workload_namespace=~\"$Namespace\", source_workload=~\"$Source\", destination_workload=~\"$Destination\"},destination_app)"
    }
   }
  ]
 },
 "panels": [
  { "title": "TLS通信", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TLSハンドシェイクの失敗数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_ssl_connection_error{pod=~\"^$Source.*$\",namespace=~\"$Namespace\", cluster_name=~\".*\\\\|$DestinationVersion\\\\|$DestinationApp.*\"}[5m])) by (pod,cluster_name) * 60",
     "legendFormat": "{{ pod }} ⇄ {{ cluster_name }}"
    }
   ]
  },
  {
   "title": "TLSハンドシェイク中の証明書署名検証の失敗数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_ssl_fail_verify_no_cert{pod=~\"^$Source.*$\",namespace=~\"$Namespace\", cluster_name=~\".*\\\\|$DestinationVersion\\\\|$DestinationApp.*\"}[5m])) by (pod,cluster_name) * 60",
     "legendFormat": "{{ pod }} ⇄ {{ cluster_name }}"
    }
   ]
  }
 ]
}